### ISSUE TITLE
Admins can log in

### ISSUE THREAD

**Issue by sudhanvarajesh-tamu** [tamu-edu-students/TopMate-Clone#11]
As an admin,
So that I can access my dashboard,
I want to use my username and password to log in.

**Comment by dalton-avery** [comment]
Log in functionality:
	- User table/controller (CRUD)
	- User_sessions table/controller (CRUD)
	- validate email format
	- validate email exists
	- validate password is not empty
	- pull account with form information
		- if account exists 
			- validate password (encrypted in db)
			- add session to user_sessions (JWT)
			- redirect to root/dashboard
		- else throw user not found (show error in ui)
